name: Packer Status Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  packer-check:
    name: "Packer format and validation check"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug secrets
        run: |
          echo "AWS_REGION=${{ secrets.AWS_REGION }}"

      - name: create variables
        run: |
          cat <<EOF > variables.pkrvars.hcl
          aws_source_ami = "${{ secrets.AWS_SOURCE_AMI }}"
          ami_name       = "${{ secrets.AMI_NAME }}"
          instance_type  = "${{ secrets.INSTANCE_TYPE }}"
          aws_region     = "${{ secrets.AWS_REGION }}"
          ssh_username   = "${{ secrets.SSH_USERNAME }}"
          EOF

      - name: Set up packer
        uses: hashicorp/setup-packer@v3

      - name: Initialize packer
        run: packer init .

      - name: Format packer
        run: packer fmt -check -recursive .

      - name: Run Packer Validate
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SOURCE_AMI: ${{ secrets.AWS_SOURCE_AMI }}
          INSTANCE_TYPE: ${{ secrets.INSTANCE_TYPE }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          AMI_NAME: ${{ secrets.AMI_NAME }}
        run: |
          packer validate .
